export { setAnalyticsEnabled, trackEvent } from './analytics'
export { playNotificationSound } from './audio'
export { preloadAndNavigate } from './contextPreload'
export { downloadMediaFile } from './download'
export { isFullEmojiText } from './emoji'
export { fetchEmojiLottie, splitEmojis } from './emojiLottie'
export { getTrendingGifs, searchGifs } from './gifSearch'
export type { GifResult } from './gifSearch'
export { sanitizeMatrixHtml } from './htmlSanitizer'
export { localizedText } from './localizedText'
export { htmlToPlainText, renderMarkdownForMatrix } from './markdown'
export { handleMatrixLinkClick } from './matrixLinks'
export { createSpeechRecognizer, isSpeechRecognitionSupported } from './speechToText'
export type { SpeechRecognitionResult } from './speechToText'
export { getSystemLanguage, translateText } from './translate'
export { cn, escapeHtml } from './utils'
