import { existsSync, readFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import antfu from '@antfu/eslint-config'
import eslintConfigPrettier from 'eslint-config-prettier/flat'

// Globals generated by unplugin-auto-import (ref/computed/useRouter/useI18n/...).
// The file is a build artifact (gitignored); fall back to {} before the first build.
const autoImportGlobalsPath = fileURLToPath(new URL('./apps/desktop/.eslintrc-auto-import.json', import.meta.url))
const autoImportGlobals = existsSync(autoImportGlobalsPath)
  ? JSON.parse(readFileSync(autoImportGlobalsPath, 'utf8')).globals
  : {}

export default antfu(
  {
    vue: true,
    typescript: true,
    stylistic: false,
    formatters: false,
    ignores: [
      '.claude/**',
      '.opencode/**',
      '.github/prompts/**',
      '.github/skills/**',
      '.planning/**',
      '.playwright-cli/**',
      'design/stitch/**',
      'docs/superpowers/**',
      'output/playwright/**',
      'openspec/**',
      'out/**',
      'release/**',
      'apps/desktop/src/auto-imports.d.ts',
      'apps/desktop/src/components.d.ts',
      'apps/desktop/.eslintrc-auto-import.json',
    ],
  },
  eslintConfigPrettier,
  {
    files: ['pnpm-workspace.yaml'],
    rules: {
      'yaml/plain-scalar': 'off',
    },
  },
  {
    files: ['apps/desktop/src/**/*.{ts,vue}'],
    languageOptions: {
      globals: autoImportGlobals,
    },
  },
)
