/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AllAppsPopover: typeof import('./app/components/workspace/AllAppsPopover.vue')['default']
    AppLayout: typeof import('./app/components/AppLayout.vue')['default']
    ConfirmDialog: typeof import('./shared/components/ConfirmDialog.vue')['default']
    ConfirmDialogHost: typeof import('./shared/components/ConfirmDialogHost.vue')['default']
    ErrorBoundary: typeof import('./app/components/ErrorBoundary.vue')['default']
    GlobalOverlayHost: typeof import('./app/components/GlobalOverlayHost.vue')['default']
    GlobalSearchDialog: typeof import('./app/components/GlobalSearchDialog.vue')['default']
    NetworkStatusBar: typeof import('./app/components/NetworkStatusBar.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    StartupSkeleton: typeof import('./app/components/StartupSkeleton.vue')['default']
    WatermarkOverlay: typeof import('./app/components/WatermarkOverlay.vue')['default']
    WindowTitleBar: typeof import('./app/components/window/WindowTitleBar.vue')['default']
    WorkspaceAppRail: typeof import('./app/components/workspace/WorkspaceAppRail.vue')['default']
    WorkspaceLayout: typeof import('./app/components/workspace/WorkspaceLayout.vue')['default']
    WorkspacePageFrame: typeof import('./app/components/workspace/WorkspacePageFrame.vue')['default']
    WorkspaceResizablePane: typeof import('./app/components/workspace/WorkspaceResizablePane.vue')['default']
  }
}
