/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by unplugin-vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-resolver' {
  export type ParamParserCustom = never
}

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/announcements': RouteRecordInfo<
      '/announcements',
      '/announcements',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/approvals': RouteRecordInfo<
      '/approvals',
      '/approvals',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/attendance': RouteRecordInfo<
      '/attendance',
      '/attendance',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/bitable': RouteRecordInfo<
      '/bitable',
      '/bitable',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calendar': RouteRecordInfo<
      '/calendar',
      '/calendar',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/calls': RouteRecordInfo<
      '/calls',
      '/calls',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/contacts': RouteRecordInfo<
      '/contacts',
      '/contacts',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dm/': RouteRecordInfo<
      '/dm/',
      '/dm',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/dm/[roomId]': RouteRecordInfo<
      '/dm/[roomId]',
      '/dm/:roomId',
      { roomId: ParamValue<true> },
      { roomId: ParamValue<false> },
      | never
    >,
    '/docs/': RouteRecordInfo<
      '/docs/',
      '/docs',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/docs/[docId]': RouteRecordInfo<
      '/docs/[docId]',
      '/docs/:docId',
      { docId: ParamValue<true> },
      { docId: ParamValue<false> },
      | never
    >,
    '/email': RouteRecordInfo<
      '/email',
      '/email',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/login': RouteRecordInfo<
      '/login',
      '/login',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/mindmap': RouteRecordInfo<
      '/mindmap',
      '/mindmap',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/minutes': RouteRecordInfo<
      '/minutes',
      '/minutes',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/okr': RouteRecordInfo<
      '/okr',
      '/okr',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization/': RouteRecordInfo<
      '/organization/',
      '/organization',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/organization/[section]': RouteRecordInfo<
      '/organization/[section]',
      '/organization/:section',
      { section: ParamValue<true> },
      { section: ParamValue<false> },
      | never
    >,
    '/projects/': RouteRecordInfo<
      '/projects/',
      '/projects',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/projects/[projectId]/': RouteRecordInfo<
      '/projects/[projectId]/',
      '/projects/:projectId',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    '/projects/[projectId]/settings': RouteRecordInfo<
      '/projects/[projectId]/settings',
      '/projects/:projectId/settings',
      { projectId: ParamValue<true> },
      { projectId: ParamValue<false> },
      | never
    >,
    '/reports': RouteRecordInfo<
      '/reports',
      '/reports',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/rooms': RouteRecordInfo<
      '/rooms',
      '/rooms',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/server/[serverId]/channel/[channelId]': RouteRecordInfo<
      '/server/[serverId]/channel/[channelId]',
      '/server/:serverId/channel/:channelId',
      { serverId: ParamValue<true>, channelId: ParamValue<true> },
      { serverId: ParamValue<false>, channelId: ParamValue<false> },
      | never
    >,
    '/settings': RouteRecordInfo<
      '/settings',
      '/settings',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/survey': RouteRecordInfo<
      '/survey',
      '/survey',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/tasks': RouteRecordInfo<
      '/tasks',
      '/tasks',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/workplace': RouteRecordInfo<
      '/workplace',
      '/workplace',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
  }

  /**
   * Route file to route info map by unplugin-vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/announcements.vue': {
      routes:
        | '/announcements'
      views:
        | never
    }
    'src/pages/approvals.vue': {
      routes:
        | '/approvals'
      views:
        | never
    }
    'src/pages/attendance.vue': {
      routes:
        | '/attendance'
      views:
        | never
    }
    'src/pages/bitable.vue': {
      routes:
        | '/bitable'
      views:
        | never
    }
    'src/pages/calendar.vue': {
      routes:
        | '/calendar'
      views:
        | never
    }
    'src/pages/calls.vue': {
      routes:
        | '/calls'
      views:
        | never
    }
    'src/pages/contacts.vue': {
      routes:
        | '/contacts'
      views:
        | never
    }
    'src/pages/dm/index.vue': {
      routes:
        | '/dm/'
      views:
        | never
    }
    'src/pages/dm/[roomId].vue': {
      routes:
        | '/dm/[roomId]'
      views:
        | never
    }
    'src/pages/docs/index.vue': {
      routes:
        | '/docs/'
      views:
        | never
    }
    'src/pages/docs/[docId].vue': {
      routes:
        | '/docs/[docId]'
      views:
        | never
    }
    'src/pages/email.vue': {
      routes:
        | '/email'
      views:
        | never
    }
    'src/pages/login.vue': {
      routes:
        | '/login'
      views:
        | never
    }
    'src/pages/mindmap.vue': {
      routes:
        | '/mindmap'
      views:
        | never
    }
    'src/pages/minutes.vue': {
      routes:
        | '/minutes'
      views:
        | never
    }
    'src/pages/okr.vue': {
      routes:
        | '/okr'
      views:
        | never
    }
    'src/pages/organization/index.vue': {
      routes:
        | '/organization/'
      views:
        | never
    }
    'src/pages/organization/[section].vue': {
      routes:
        | '/organization/[section]'
      views:
        | never
    }
    'src/pages/projects/index.vue': {
      routes:
        | '/projects/'
      views:
        | never
    }
    'src/pages/projects/[projectId]/index.vue': {
      routes:
        | '/projects/[projectId]/'
      views:
        | never
    }
    'src/pages/projects/[projectId]/settings.vue': {
      routes:
        | '/projects/[projectId]/settings'
      views:
        | never
    }
    'src/pages/reports.vue': {
      routes:
        | '/reports'
      views:
        | never
    }
    'src/pages/rooms.vue': {
      routes:
        | '/rooms'
      views:
        | never
    }
    'src/pages/server/[serverId]/channel/[channelId].vue': {
      routes:
        | '/server/[serverId]/channel/[channelId]'
      views:
        | never
    }
    'src/pages/settings.vue': {
      routes:
        | '/settings'
      views:
        | never
    }
    'src/pages/survey.vue': {
      routes:
        | '/survey'
      views:
        | never
    }
    'src/pages/tasks.vue': {
      routes:
        | '/tasks'
      views:
        | never
    }
    'src/pages/workplace.vue': {
      routes:
        | '/workplace'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}
